name = "remix-cloudflare-workers"
type = "javascript"

zone_id = ""
account_id = ""
route = ""

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format = "modules"
main = "./shim.mjs"
